### ISSUE TITLE
Trying to install Homebridge-yamaha

### ISSUE THREAD

**Issue by dazza120** [neonightmare/homebridge-yamaha#18]
Hi i'm trying to install this plug in for the WXA-50 that i'm getting next week just wanted to get the Config.json file setup but i'm running into issues installing it in terminal via Mac 

This is what i get:

npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130

> mdns@2.3.4 install /usr/local/lib/node_modules/homebridge-yamaha/node_modules/mdns
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/homebridge-yamaha/node_modules/mdns/build'
gyp ERR! System Darwin 16.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge-yamaha/node_modules/mdns
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mdns@2.3.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mdns@2.3.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/thor/.npm/_logs/2018-02-17T13_40_36_112Z-debug.log
Thor:~ thor$

**Comment by NorthernMan54** [comment]
Have you tried running the npm install command with sudo?  ie

sudo npm install -g homebridge-yamaha

**Comment by dazza120** [comment]
Hi thanks i have done sudo npm install -g --unsafe-perm homebridge-yamaha it gave me warnings but it installed but now i can't get homebridge running the config.json file it just comes up with errors and home bridge doesn't lunch :( 

┌─────────────────────────────────────────────────────────┐
│                 npm update check failed                 │
│           Try running with sudo or get access           │
│          to the local update config store via           │
│ sudo chown -R $USER:$(id -gn $USER) /Users/thor/.config │
└─────────────────────────────────────────────────────────┘
[2018-2-17 14:09:01] Loaded plugin: homebridge-nest
[2018-2-17 14:09:01] Registering platform 'homebridge-nest.Nest'
[2018-2-17 14:09:01] ---
[2018-2-17 14:09:01] Loaded plugin: homebridge-platform-wemo
[2018-2-17 14:09:01] Registering platform 'homebridge-platform-wemo.BelkinWeMo'
[2018-2-17 14:09:01] ---
[2018-2-17 14:09:02] Loaded plugin: homebridge-yamaha
[2018-2-17 14:09:02] Registering accessory 'homebridge-yamaha.YamahaAVR'
[2018-2-17 14:09:02] Registering platform 'homebridge-yamaha.YamahaAVR'
[2018-2-17 14:09:02] ---
[2018-2-17 14:09:02] There was a problem reading your config.json file.
[2018-2-17 14:09:02] Please try pasting your config.json file here to validate it: http://jsonlint.com
[2018-2-17 14:09:02] 
/usr/local/lib/node_modules/homebridge/lib/server.js:207
    throw err;
    ^

SyntaxError: Unexpected token ] in JSON at position 1423
    at JSON.parse (<anonymous>)
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:201:19)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:57:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
Thor:~ thor$

**Comment by NorthernMan54** [comment]
Your config.json has problem.  Double check the structure

**Comment by dazza120** [comment]
Hi thanks for the fast reply i can't say I've ever been good at doing config.json files :( This is what i've got the nest and the wemo part works fine if i take out the yamaha bit i'm lost where i went wrong. Can you help? Please

{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
        "port":51826,
		"pin": "031-45-154"
	},
					"platforms": [
				    {
				        "platform": "Nest",
				        "token" : "**********************************************",
				        "clientId": "****************",
				        "clientSecret": "******************",
				        "code": "**********",
				        "username" : "*************",
				        "password" : "*************"
							},
								{
									"platform": "BelkinWeMo",
									"name": "WeMo Platform",
									"manualDevices": ["http://192.168.1.27:49153/setup.xml",
										"http://192.168.1.27:49153/setup.xml",
										"http://192.168.1.17:49153/setup.xml",
										"http://192.168.1.15:49153/setup.xml",
										"http://192.168.1.19:49153/setup.xml",
										"http://192.168.1.24:49153/setup.xml"],
									"discovery": false,
									"expected_accessories" : "6",
									"timeout" : "25",
									"no_motion_timer": "60",
									"homekit_safe" : "1"
								},
	        {
						"platform": "YamahaAVR",
            "play_volume": -48,
            "setMainInputTo": "Airplay",
            "show_input_name": "yes",
            "manual_addresses": {
                "Yamaha": "192.168.1.29" 
							},
							]
		}

**Comment by NorthernMan54** [comment]
The last comma doesn’t belong

**Comment by dazza120** [comment]
what the } ?

**Comment by NorthernMan54** [comment]
Sorry it is more than the comma , it also needs a bracket...

It should be

{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},
	"platforms": [{
			"platform": "Nest",
			"token": "",
			"clientId": "",
			"clientSecret": "",
			"code": "",
			"username": "",
			"password": "**"
		},
		{
			"platform": "BelkinWeMo",
			"name": "WeMo Platform",
			"manualDevices": ["http://192.168.1.27:49153/setup.xml",
				"http://192.168.1.27:49153/setup.xml",
				"http://192.168.1.17:49153/setup.xml",
				"http://192.168.1.15:49153/setup.xml",
				"http://192.168.1.19:49153/setup.xml",
				"http://192.168.1.24:49153/setup.xml"
			],
			"discovery": false,
			"expected_accessories": "6",
			"timeout": "25",
			"no_motion_timer": "60",
			"homekit_safe": "1"
		},
		{
			"platform": "YamahaAVR",
			"play_volume": -48,
			"setMainInputTo": "Airplay",
			"show_input_name": "yes",
			"manual_addresses": {
				"Yamaha": "192.168.1.29"
			}
		}
	]
}

**Comment by dazza120** [comment]
Oh my word Thank you very much, That was much appreciated. Now all i have to do is wait on my amp to come and then change the amp i.p. address in my router ie make it a static i.p. to the one i put in the config.json file and i should be good to use this in home kit? Once again thanks very much 👍 :)

**Comment by NorthernMan54** [comment]
I didn’t bother with making mine static, and the address has been the same for over a year.   I just use the auto discovery.

**Comment by dazza120** [comment]
Awesome thanks, yeah i just assign them on the router via Mac address and put there name just so i ca see every device on my network so i know if something is connected that shouldn't be connected really thats the only reason why I've done it and spent ages before going around each device and  binding the Mac address so I've got to keep up with it now it's an OCD thing now lol. Once again thank you very much 👍
