### ISSUE TITLE
New to this scene

### ISSUE THREAD

**Issue by Azza1979** [neonightmare/homebridge-yamaha#6]
Good morning i have home bridge running for my wemo platform and have just used this yamaha platform as well. Forgive me for asking this silly question but are the only commands to turn the power state on or off and change volume ? or am i missing something. Once again I'm new to this and thank you for your time and code. Cheers

**Comment by SphtKr** [comment]
So far yes. HomeKit doesn't have standard characteristics for media playback. Even the volume characteristic is a custom-defined characteristic that probably won't work in all HomeKit apps and doesn't work with Siri. Hopefully, Apple will include some media device control characteristics in the future, but so far the available options don't apply (for instance, I was thinking about using a fan device's clockwise/anticlockwise control to skip tracks back/forward, but that would be quite a hack).

**Comment by florian-muc** [comment]
The Elgato Eve app does support Audio Volume and even has a nice icon for it.

**Comment by SphtKr** [comment]
Yup, that's very new and surprising. It's encouraged me to define a whole new set of custom characteristics for an iTunes plugin i'm planning...but they all still have to be implemented into Eve or another app. Here's hoping Apple adds some media control characteristics at WWDC!
